### ISSUE TITLE
Bug: Errors occurred when server shutdown and SST handles request

### ISSUE THREAD

**Issue by Ranzeplay** [kmcsr/smart_servertime_mcdr#1]
When the server has been shut down due to no players online for a while by SST, some errors could occur, displayed in Traceback
```
Traceback (most recent call last):
  File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\proxy_server.py", line 44, in h
    if self._mcserver.handle(cli, addr):
  File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 38, in handle
    _, pid, data = recv_package(conn)
  File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 115, in recv_package
    pid = read_varint(pr)
  File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 134, in read_varint
    bt = r.read(1)[0]
```
And high CPU usage. I use an i3-8100T for my server, but MCDR used 60% CPU when SST is enabled.

**Comment by zyxkad** [comment]
> When the server has been shut down due to no players online for a while by SST, some errors could occur, displayed in Traceback
> 
> ```
> Traceback (most recent call last):
>   File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\proxy_server.py", line 44, in h
>     if self._mcserver.handle(cli, addr):
>   File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 38, in handle
>     _, pid, data = recv_package(conn)
>   File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 115, in recv_package
>     pid = read_varint(pr)
>   File "plugins\SmartServerTime-v1.0.0.mcdr\smart_servertime\minecraft_server.py", line 134, in read_varint
>     bt = r.read(1)[0]
> ```
> 
> And high CPU usage. I use an i3-8100T for my server, but MCDR used 60% CPU when SST is enabled.

Please give the full traceback, your traceback is truncated

**Comment by zyxkad** [comment]
> And high CPU usage. I use an i3-8100T for my server, but MCDR used 60% CPU when SST is enabled.

Do you have another plugin(s) loaded? I don't think SST will use much CPU :(

**Comment by Ranzeplay** [comment]
Okay, I’ll use some profiling tools to analyze the issue.

**Comment by zyxkad** [comment]
Hello, are you still have this problem in [v1.1.0](https://github.com/kmcsr/smart_servertime_mcdr/releases/tag/v1.1.0)? @Ranzeplay

**Comment by Ranzeplay** [comment]
I'll try it, thank you very much :)

**Comment by Ranzeplay** [comment]
It seems ok now, I couldn't reproduce it anymore.
